/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 21 19:42:46 GMT 2021
 */

package org.jsoup.select;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.regex.Pattern;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attribute;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.FormElement;
import org.jsoup.nodes.PseudoTextElement;
import org.jsoup.parser.ParseSettings;
import org.jsoup.parser.Tag;
import org.jsoup.select.CombiningEvaluator;
import org.jsoup.select.Elements;
import org.jsoup.select.Evaluator;
import org.jsoup.select.StructuralEvaluator;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Evaluator_ESTest extends Evaluator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Tag tag0 = Tag.valueOf(":last-child");
      Element element0 = new Element(tag0, ":last-child");
      element0.html(":last-child");
      Evaluator.MatchText evaluator_MatchText0 = new Evaluator.MatchText();
      boolean boolean0 = evaluator_MatchText0.matches(element0, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Evaluator.MatchText evaluator_MatchText0 = new Evaluator.MatchText();
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      Tag tag0 = Tag.valueOf("F\"9E*/qS[sO<", parseSettings0);
      Attributes attributes0 = new Attributes();
      PseudoTextElement pseudoTextElement0 = new PseudoTextElement(tag0, "F\"9E*/qS[sO<", attributes0);
      boolean boolean0 = evaluator_MatchText0.matches(pseudoTextElement0, pseudoTextElement0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Element element0 = new Element("org.jsoup.select.Evaluator$AttributeStarting");
      Evaluator.IsEmpty evaluator_IsEmpty0 = new Evaluator.IsEmpty();
      boolean boolean0 = evaluator_IsEmpty0.matches(element0, element0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Document document0 = Document.createShell("");
      Evaluator.IsOnlyOfType evaluator_IsOnlyOfType0 = new Evaluator.IsOnlyOfType();
      Element element0 = document0.head();
      boolean boolean0 = evaluator_IsOnlyOfType0.matches(element0, element0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Document document0 = Document.createShell("");
      Evaluator.IsOnlyOfType evaluator_IsOnlyOfType0 = new Evaluator.IsOnlyOfType();
      boolean boolean0 = evaluator_IsOnlyOfType0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Tag tag0 = Tag.valueOf("nth-child");
      CDataNode cDataNode0 = new CDataNode("");
      Attributes attributes0 = cDataNode0.attributes();
      FormElement formElement0 = new FormElement(tag0, "", attributes0);
      Evaluator.IsOnlyChild evaluator_IsOnlyChild0 = new Evaluator.IsOnlyChild();
      Document document0 = Document.createShell("nth-child");
      formElement0.appendTo(document0);
      boolean boolean0 = evaluator_IsOnlyChild0.matches(formElement0, formElement0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Tag tag0 = Tag.valueOf("nth-child");
      CDataNode cDataNode0 = new CDataNode("");
      Attributes attributes0 = cDataNode0.attributes();
      FormElement formElement0 = new FormElement(tag0, "", attributes0);
      Evaluator.IsOnlyChild evaluator_IsOnlyChild0 = new Evaluator.IsOnlyChild();
      Document document0 = Document.createShell("nth-child");
      Element element0 = document0.body();
      boolean boolean0 = evaluator_IsOnlyChild0.matches(formElement0, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Element element0 = new Element("org.jsoup.select.Evaluator$AttributeStarting");
      Evaluator.IsOnlyChild evaluator_IsOnlyChild0 = new Evaluator.IsOnlyChild();
      boolean boolean0 = evaluator_IsOnlyChild0.matches(element0, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Document document0 = new Document("frame");
      Document document1 = document0.normalise();
      Evaluator.IsRoot evaluator_IsRoot0 = new Evaluator.IsRoot();
      boolean boolean0 = evaluator_IsRoot0.matches(document0, document1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Evaluator.IsRoot evaluator_IsRoot0 = new Evaluator.IsRoot();
      Element element0 = new Element("id");
      boolean boolean0 = evaluator_IsRoot0.matches(element0, element0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Document document0 = Document.createShell(".z|lYq0|]k");
      Evaluator.IsFirstChild evaluator_IsFirstChild0 = new Evaluator.IsFirstChild();
      Element element0 = document0.body();
      boolean boolean0 = evaluator_IsFirstChild0.matches(document0, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Document document0 = Document.createShell("");
      Element element0 = document0.head();
      Evaluator.IsLastOfType evaluator_IsLastOfType0 = new Evaluator.IsLastOfType();
      int int0 = evaluator_IsLastOfType0.calculatePosition(document0, element0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Evaluator.IsNthLastChild evaluator_IsNthLastChild0 = new Evaluator.IsNthLastChild(0, 0);
      String string0 = evaluator_IsNthLastChild0.toString();
      assertEquals(":nth-last-child(0)", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Evaluator.IsLastOfType evaluator_IsLastOfType0 = new Evaluator.IsLastOfType();
      Document document0 = Document.createShell("^x>uNw?9X&QerE>\"");
      StructuralEvaluator.ImmediateParent structuralEvaluator_ImmediateParent0 = new StructuralEvaluator.ImmediateParent(evaluator_IsLastOfType0);
      Element element0 = document0.head();
      boolean boolean0 = structuralEvaluator_ImmediateParent0.matches(document0, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Document document0 = Document.createShell("\"^x>uNw?9X&QerE>\"");
      Element element0 = document0.body();
      Evaluator.IsFirstOfType evaluator_IsFirstOfType0 = new Evaluator.IsFirstOfType();
      boolean boolean0 = evaluator_IsFirstOfType0.matches(element0, element0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Document document0 = Document.createShell("");
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      Element element0 = document0.body();
      boolean boolean0 = evaluator_IsLastChild0.matches(document0, element0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Document document0 = Document.createShell("");
      Element element0 = document0.head();
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      boolean boolean0 = evaluator_IsLastChild0.matches(document0, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Document document0 = new Document("allowfullscreen");
      document0.prependChild(document0);
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      boolean boolean0 = evaluator_IsLastChild0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Document document0 = new Document("allowfullscreen");
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      boolean boolean0 = evaluator_IsLastChild0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Evaluator.IndexEquals evaluator_IndexEquals0 = new Evaluator.IndexEquals(0);
      Tag tag0 = Tag.valueOf("tG=H|u&CR");
      Attributes attributes0 = new Attributes();
      FormElement formElement0 = new FormElement(tag0, "tG=H|u&CR", attributes0);
      boolean boolean0 = evaluator_IndexEquals0.matches(formElement0, formElement0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Evaluator.IsFirstChild evaluator_IsFirstChild0 = new Evaluator.IsFirstChild();
      Document document0 = new Document("Ld!mZs");
      Evaluator.IsNthOfType evaluator_IsNthOfType0 = new Evaluator.IsNthOfType((-57557325), 4751);
      Evaluator[] evaluatorArray0 = new Evaluator[9];
      evaluatorArray0[0] = (Evaluator) evaluator_IsNthOfType0;
      evaluatorArray0[1] = (Evaluator) evaluator_IsFirstChild0;
      evaluatorArray0[2] = (Evaluator) evaluator_IsFirstChild0;
      evaluatorArray0[3] = (Evaluator) evaluator_IsFirstChild0;
      evaluatorArray0[4] = (Evaluator) evaluator_IsNthOfType0;
      Evaluator.IndexEquals evaluator_IndexEquals0 = new Evaluator.IndexEquals((-57557325));
      evaluatorArray0[5] = (Evaluator) evaluator_IndexEquals0;
      CombiningEvaluator.Or combiningEvaluator_Or0 = new CombiningEvaluator.Or(evaluatorArray0);
      // Undeclared exception!
      try { 
        combiningEvaluator_Or0.matches((Element) null, document0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.CombiningEvaluator$Or", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Document document0 = new Document("frame");
      Elements elements0 = document0.getElementsByIndexGreaterThan((-1102));
      assertFalse(elements0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Evaluator.IndexGreaterThan evaluator_IndexGreaterThan0 = new Evaluator.IndexGreaterThan(195);
      Document document0 = Document.createShell("t%5(kP%cL");
      boolean boolean0 = evaluator_IndexGreaterThan0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.htmlDefault;
      Tag tag0 = Tag.valueOf("h", parseSettings0);
      CDataNode cDataNode0 = new CDataNode("html");
      Attributes attributes0 = cDataNode0.attributes();
      FormElement formElement0 = new FormElement(tag0, "GQpUSOsU;i~F'j~Cj:x", attributes0);
      Document document0 = Document.createShell("html");
      Evaluator.IndexLessThan evaluator_IndexLessThan0 = new Evaluator.IndexLessThan((-1049));
      boolean boolean0 = evaluator_IndexLessThan0.matches(formElement0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Evaluator.IndexLessThan evaluator_IndexLessThan0 = new Evaluator.IndexLessThan(1);
      Document document0 = Document.createShell("[:last-of-type^=:last-of-type]");
      Element element0 = document0.body();
      boolean boolean0 = evaluator_IndexLessThan0.matches(element0, document0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Evaluator.IndexLessThan evaluator_IndexLessThan0 = new Evaluator.IndexLessThan(1277);
      Document document0 = new Document("#");
      boolean boolean0 = evaluator_IndexLessThan0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Evaluator.AttributeWithValueStarting evaluator_AttributeWithValueStarting0 = new Evaluator.AttributeWithValueStarting("'charset'", "'charset'");
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Evaluator.AttributeWithValueEnding evaluator_AttributeWithValueEnding0 = null;
      try {
        evaluator_AttributeWithValueEnding0 = new Evaluator.AttributeWithValueEnding("[9tuz8x`2h+=org.jsoup.select.evaluator$attributewithvaluenot]", "\"");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Tag tag0 = Tag.valueOf("jetA*i");
      Attributes attributes0 = new Attributes();
      FormElement formElement0 = new FormElement(tag0, "t", attributes0);
      Pattern pattern0 = Pattern.compile("]", (-102441799));
      Evaluator.AttributeWithValueMatching evaluator_AttributeWithValueMatching0 = new Evaluator.AttributeWithValueMatching("jetA*i", pattern0);
      boolean boolean0 = evaluator_AttributeWithValueMatching0.matches(formElement0, formElement0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Evaluator.AttributeWithValueContaining evaluator_AttributeWithValueContaining0 = new Evaluator.AttributeWithValueContaining("\"':last-child", "\"]");
      ParseSettings parseSettings0 = new ParseSettings(true, false);
      Tag tag0 = Tag.valueOf("\"]", parseSettings0);
      Attributes attributes0 = new Attributes();
      Attribute attribute0 = new Attribute("\"':last-child", "\"':last-child");
      Attributes attributes1 = attributes0.put(attribute0);
      PseudoTextElement pseudoTextElement0 = new PseudoTextElement(tag0, "\"':last-child", attributes1);
      boolean boolean0 = evaluator_AttributeWithValueContaining0.matches(pseudoTextElement0, pseudoTextElement0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Evaluator.AttributeWithValueContaining evaluator_AttributeWithValueContaining0 = new Evaluator.AttributeWithValueContaining("m", "m");
      Document document0 = Document.createShell("m");
      Element element0 = document0.attr("m", "m");
      boolean boolean0 = evaluator_AttributeWithValueContaining0.matches(element0, document0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Document document0 = new Document("allowfullscreen");
      Evaluator.AttributeWithValueContaining evaluator_AttributeWithValueContaining0 = new Evaluator.AttributeWithValueContaining("T(HZPpFs5|*el", "figcaption");
      boolean boolean0 = evaluator_AttributeWithValueContaining0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Tag tag0 = Tag.valueOf("h3", (ParseSettings) null);
      Element element0 = new Element(tag0, ":%s(%dn%+d)");
      Evaluator.AttributeWithValueEnding evaluator_AttributeWithValueEnding0 = new Evaluator.AttributeWithValueEnding("o/?}_LqgV", "':last-child");
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.put("o/?}_LqgV", true);
      FormElement formElement0 = new FormElement(tag0, "':last-child", attributes1);
      boolean boolean0 = evaluator_AttributeWithValueEnding0.matches(element0, formElement0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Element element0 = new Element("org.jsoup.select.Evaluator$AttributeStarting");
      Evaluator.AttributeWithValueEnding evaluator_AttributeWithValueEnding0 = new Evaluator.AttributeWithValueEnding("\"]]=/vT?;&<YYv", "org.jsoup.nodes.Attribute");
      boolean boolean0 = evaluator_AttributeWithValueEnding0.matches(element0, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Document document0 = new Document("allowfullscreen");
      Evaluator.AttributeWithValueStarting evaluator_AttributeWithValueStarting0 = new Evaluator.AttributeWithValueStarting("T(HZPpFs5|*el", "T(HZPpFs5|*el");
      boolean boolean0 = evaluator_AttributeWithValueStarting0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Evaluator.AttributeWithValueNot evaluator_AttributeWithValueNot0 = new Evaluator.AttributeWithValueNot("h3", "h3");
      Tag tag0 = Tag.valueOf("h3", (ParseSettings) null);
      Element element0 = new Element(tag0, ":%s(%dn%+d)");
      Document document0 = Document.createShell(":%s(%dn%+d)");
      boolean boolean0 = evaluator_AttributeWithValueNot0.matches(element0, document0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Document document0 = Document.createShell("t%5(kP%cL");
      Evaluator.AttributeWithValue evaluator_AttributeWithValue0 = new Evaluator.AttributeWithValue("9TUZ8x`2H+", "org.jsoup.select.Evaluator$AttributeWithValueNot");
      boolean boolean0 = evaluator_AttributeWithValue0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Element element0 = new Element("org.jsoup.select.Evaluator$AttributeStarting");
      Evaluator.AttributeStarting evaluator_AttributeStarting0 = new Evaluator.AttributeStarting("EOF");
      Tag tag0 = Tag.valueOf("\"]]=/vT?;&<YYv");
      CDataNode cDataNode0 = new CDataNode("\"ylP9<Zzv}VUvN");
      Attributes attributes0 = cDataNode0.attributes();
      Element element1 = new Element(tag0, ":", attributes0);
      boolean boolean0 = evaluator_AttributeStarting0.matches(element0, element1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Evaluator.AttributeWithValueNot evaluator_AttributeWithValueNot0 = new Evaluator.AttributeWithValueNot("t|A_9\"dFh(fc", "t|A_9\"dFh(fc");
      Document document0 = new Document("t|A_9\"dFh(fc");
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_AttributeWithValueNot0);
      boolean boolean0 = structuralEvaluator_Has0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Evaluator.AllElements evaluator_AllElements0 = new Evaluator.AllElements();
      String string0 = evaluator_AllElements0.toString();
      assertEquals("*", string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Evaluator.IsFirstOfType evaluator_IsFirstOfType0 = new Evaluator.IsFirstOfType();
      String string0 = evaluator_IsFirstOfType0.toString();
      assertEquals(":first-of-type", string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Evaluator.AttributeWithValueContaining evaluator_AttributeWithValueContaining0 = new Evaluator.AttributeWithValueContaining("C/c}#u{^BBl,}", "]]=/vT?;&<YYv");
      String string0 = evaluator_AttributeWithValueContaining0.toString();
      assertEquals("[c/c}#u{^bbl,}*=]]=/vt?;&<yyv]", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Document document0 = new Document("allowfullscreen");
      Document document1 = document0.normalise();
      Evaluator.IsEmpty evaluator_IsEmpty0 = new Evaluator.IsEmpty();
      boolean boolean0 = evaluator_IsEmpty0.matches(document1, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Evaluator.Tag evaluator_Tag0 = new Evaluator.Tag("frame");
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_Tag0);
      String string0 = structuralEvaluator_Not0.toString();
      assertEquals(":notframe", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Evaluator.ContainsOwnText evaluator_ContainsOwnText0 = new Evaluator.ContainsOwnText("T(HZPpFs5|*el");
      String string0 = evaluator_ContainsOwnText0.toString();
      assertEquals(":containsOwn(t(hzppfs5|*el)", string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Evaluator.ContainsOwnText evaluator_ContainsOwnText0 = new Evaluator.ContainsOwnText("T(HZPpFs5|*el");
      Document document0 = new Document("allowfullscreen");
      boolean boolean0 = evaluator_ContainsOwnText0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Evaluator.AttributeStarting evaluator_AttributeStarting0 = new Evaluator.AttributeStarting("figcaption");
      String string0 = evaluator_AttributeStarting0.toString();
      assertEquals("[^figcaption]", string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Evaluator.IsFirstChild evaluator_IsFirstChild0 = new Evaluator.IsFirstChild();
      String string0 = evaluator_IsFirstChild0.toString();
      assertEquals(":first-child", string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Evaluator.Attribute evaluator_Attribute0 = new Evaluator.Attribute(":last-of-type");
      String string0 = evaluator_Attribute0.toString();
      assertEquals("[:last-of-type]", string0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Element element0 = new Element("org.jsoup.select.Evaluator$AttributeStarting");
      Elements elements0 = element0.getElementsByAttribute("org.jsoup.nodes.Attribute");
      assertEquals(0, elements0.size());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Evaluator.TagEndsWith evaluator_TagEndsWith0 = new Evaluator.TagEndsWith("WH}:CO=T_HqJgC4)");
      String string0 = evaluator_TagEndsWith0.toString();
      assertEquals("WH}:CO=T_HqJgC4)", string0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Document document0 = new Document("allowfullscreen");
      Evaluator.TagEndsWith evaluator_TagEndsWith0 = new Evaluator.TagEndsWith(":containsOwn(t(hzppfs5|*el)");
      boolean boolean0 = evaluator_TagEndsWith0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Evaluator.IsLastOfType evaluator_IsLastOfType0 = new Evaluator.IsLastOfType();
      String string0 = evaluator_IsLastOfType0.toString();
      assertEquals(":last-of-type", string0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Evaluator.IsNthLastOfType evaluator_IsNthLastOfType0 = new Evaluator.IsNthLastOfType(465, 0);
      String string0 = evaluator_IsNthLastOfType0.toString();
      assertEquals(":nth-last-of-type(465n)", string0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Pattern pattern0 = Pattern.compile(":only-child", 16);
      Evaluator.MatchesOwn evaluator_MatchesOwn0 = new Evaluator.MatchesOwn(pattern0);
      String string0 = evaluator_MatchesOwn0.toString();
      assertEquals(":matchesOwn(:only-child)", string0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("org.jsoup.select.StructuralEvaluator$Root");
      Evaluator.MatchesOwn evaluator_MatchesOwn0 = new Evaluator.MatchesOwn(pattern0);
      Tag tag0 = Tag.valueOf("!g");
      Element element0 = new Element(tag0, "F;wq5=LilYGgq");
      boolean boolean0 = evaluator_MatchesOwn0.matches(element0, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Document document0 = new Document("=N@&T\"e~");
      Evaluator.IsNthLastChild evaluator_IsNthLastChild0 = new Evaluator.IsNthLastChild(0, 0);
      // Undeclared exception!
      try { 
        evaluator_IsNthLastChild0.calculatePosition(document0, document0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.Evaluator$IsNthLastChild", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Evaluator.IsNthLastChild evaluator_IsNthLastChild0 = new Evaluator.IsNthLastChild(29, 16);
      String string0 = evaluator_IsNthLastChild0.toString();
      assertEquals(":nth-last-child(29n+16)", string0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      String string0 = evaluator_IsLastChild0.toString();
      assertEquals(":last-child", string0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Evaluator.IndexEquals evaluator_IndexEquals0 = new Evaluator.IndexEquals((-1106));
      String string0 = evaluator_IndexEquals0.toString();
      assertEquals(":eq(-1106)", string0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Evaluator.Class evaluator_Class0 = new Evaluator.Class("jtzkgC]\u0000I]0]");
      Document document0 = Document.createShell("jtzkgC]\u0000I]0]");
      boolean boolean0 = evaluator_Class0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Evaluator.Class evaluator_Class0 = new Evaluator.Class("jtzkgC]\u0000I]0]");
      String string0 = evaluator_Class0.toString();
      assertEquals(".jtzkgC]\u0000I]0]", string0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Element element0 = new Element("id");
      Evaluator.Id evaluator_Id0 = new Evaluator.Id(":root");
      boolean boolean0 = evaluator_Id0.matches(element0, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Evaluator.Id evaluator_Id0 = new Evaluator.Id("t%5(kP%cL");
      String string0 = evaluator_Id0.toString();
      assertEquals("#t%5(kP%cL", string0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Document document0 = new Document("t|A_9\"dFh(fc");
      Evaluator.ContainsData evaluator_ContainsData0 = new Evaluator.ContainsData("t|A_9\"dFh(fc");
      boolean boolean0 = evaluator_ContainsData0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Evaluator.ContainsData evaluator_ContainsData0 = new Evaluator.ContainsData("");
      String string0 = evaluator_ContainsData0.toString();
      assertEquals(":containsData()", string0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Evaluator.IsNthOfType evaluator_IsNthOfType0 = new Evaluator.IsNthOfType(0, 0);
      String string0 = evaluator_IsNthOfType0.getPseudoClass();
      assertEquals("nth-of-type", string0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Evaluator.IsRoot evaluator_IsRoot0 = new Evaluator.IsRoot();
      String string0 = evaluator_IsRoot0.toString();
      assertEquals(":root", string0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      Document document0 = Document.createShell("");
      Evaluator.IsNthChild evaluator_IsNthChild0 = new Evaluator.IsNthChild((-785), (-785));
      int int0 = evaluator_IsNthChild0.calculatePosition(document0, document0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      Evaluator.IsNthChild evaluator_IsNthChild0 = new Evaluator.IsNthChild((-42305025), (-42305025));
      String string0 = evaluator_IsNthChild0.getPseudoClass();
      assertEquals("nth-child", string0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      Evaluator.IsOnlyChild evaluator_IsOnlyChild0 = new Evaluator.IsOnlyChild();
      String string0 = evaluator_IsOnlyChild0.toString();
      assertEquals(":only-child", string0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      Evaluator.ContainsText evaluator_ContainsText0 = new Evaluator.ContainsText("");
      Document document0 = new Document(",#");
      boolean boolean0 = evaluator_ContainsText0.matches(document0, document0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      Evaluator.ContainsText evaluator_ContainsText0 = new Evaluator.ContainsText(":has([org.jsoup.select.evaluator$isonlychild^=org.jsoup.select.evaluator$isonlychild])");
      String string0 = evaluator_ContainsText0.toString();
      assertEquals(":contains(:has([org.jsoup.select.evaluator$isonlychild^=org.jsoup.select.evaluator$isonlychild]))", string0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      Evaluator.AttributeWithValueEnding evaluator_AttributeWithValueEnding0 = new Evaluator.AttributeWithValueEnding("TmXd&bR;s", "2o;(P;jzf^S#");
      String string0 = evaluator_AttributeWithValueEnding0.toString();
      assertEquals("[tmxd&br;s$=2o;(p;jzf^s#]", string0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("si'=LkL:Yw9z_");
      Evaluator.Matches evaluator_Matches0 = new Evaluator.Matches(pattern0);
      String string0 = evaluator_Matches0.toString();
      assertEquals(":matches(si'=LkL:Yw9z_)", string0);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      ParseSettings parseSettings0 = new ParseSettings(true, true);
      Tag tag0 = Tag.valueOf("(Reb", parseSettings0);
      Attributes attributes0 = new Attributes();
      Element element0 = new Element(tag0, "];r\"Oqco0", attributes0);
      Pattern pattern0 = Pattern.compile("si'=LkL:Yw9z_");
      Evaluator.Matches evaluator_Matches0 = new Evaluator.Matches(pattern0);
      boolean boolean0 = evaluator_Matches0.matches(element0, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      Pattern pattern0 = Pattern.compile(":containsData(%s)");
      Evaluator.AttributeWithValueMatching evaluator_AttributeWithValueMatching0 = new Evaluator.AttributeWithValueMatching(":containsData(%s)", pattern0);
      String string0 = evaluator_AttributeWithValueMatching0.toString();
      assertEquals("[:containsdata(%s)~=:containsData(%s)]", string0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      Evaluator.IsEmpty evaluator_IsEmpty0 = new Evaluator.IsEmpty();
      String string0 = evaluator_IsEmpty0.toString();
      assertEquals(":empty", string0);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      Evaluator.MatchText evaluator_MatchText0 = new Evaluator.MatchText();
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_MatchText0);
      String string0 = structuralEvaluator_Not0.toString();
      assertEquals(":not:matchText", string0);
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      Evaluator.IsOnlyOfType evaluator_IsOnlyOfType0 = new Evaluator.IsOnlyOfType();
      String string0 = evaluator_IsOnlyOfType0.toString();
      assertEquals(":only-of-type", string0);
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      Evaluator.IndexGreaterThan evaluator_IndexGreaterThan0 = new Evaluator.IndexGreaterThan((-264));
      String string0 = evaluator_IndexGreaterThan0.toString();
      assertEquals(":gt(-264)", string0);
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      Evaluator.AttributeWithValueNot evaluator_AttributeWithValueNot0 = new Evaluator.AttributeWithValueNot("C].j ,`", "C].j ,`");
      String string0 = evaluator_AttributeWithValueNot0.toString();
      assertEquals("[c].j ,`!=c].j ,`]", string0);
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      Evaluator.AttributeWithValue evaluator_AttributeWithValue0 = new Evaluator.AttributeWithValue(":containsOwn(t(hzppfs5|*el)", "T(HZPpFs5|*el");
      String string0 = evaluator_AttributeWithValue0.toString();
      assertEquals("[:containsown(t(hzppfs5|*el)=t(hzppfs5|*el]", string0);
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      Evaluator.AttributeWithValueStarting evaluator_AttributeWithValueStarting0 = new Evaluator.AttributeWithValueStarting("org.jsoup.select.Evaluator$IsOnlyChild", "org.jsoup.select.Evaluator$IsOnlyChild");
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_AttributeWithValueStarting0);
      String string0 = structuralEvaluator_Has0.toString();
      assertEquals(":has([org.jsoup.select.evaluator$isonlychild^=org.jsoup.select.evaluator$isonlychild])", string0);
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      Evaluator.IndexLessThan evaluator_IndexLessThan0 = new Evaluator.IndexLessThan(5271);
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(evaluator_IndexLessThan0);
      String string0 = structuralEvaluator_ImmediatePreviousSibling0.toString();
      assertEquals(":prev:lt(5271)", string0);
  }
}
