/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 21 19:59:31 GMT 2021
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.PseudoTextElement;
import org.jsoup.parser.ParseSettings;
import org.jsoup.parser.Tag;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PseudoTextElement_ESTest extends PseudoTextElement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Tag tag0 = Tag.valueOf("3<I:-l)z>Im?yXX!");
      CDataNode cDataNode0 = new CDataNode("3<I:-l)z>Im?yXX!");
      Attributes attributes0 = cDataNode0.attributes();
      PseudoTextElement pseudoTextElement0 = new PseudoTextElement(tag0, "3<I:-l)z>Im?yXX!", attributes0);
      StringBuffer stringBuffer0 = new StringBuffer("k#N;Hc8");
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      pseudoTextElement0.outerHtmlHead(stringBuffer0, 32, document_OutputSettings0);
      assertFalse(pseudoTextElement0.hasParent());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.htmlDefault;
      Tag tag0 = Tag.valueOf("yIMS_ZXX{&MH`sA-U", parseSettings0);
      PseudoTextElement pseudoTextElement0 = new PseudoTextElement(tag0, "yIMS_ZXX{&MH`sA-U", (Attributes) null);
      Document.OutputSettings document_OutputSettings0 = pseudoTextElement0.getOutputSettings();
      pseudoTextElement0.outerHtmlTail((Appendable) null, 0, document_OutputSettings0);
      assertEquals(1, document_OutputSettings0.indentAmount());
  }
}
