/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 21 20:07:07 GMT 2021
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.XmlDeclaration;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XmlDeclaration_ESTest extends XmlDeclaration_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("F", true);
      Attributes attributes0 = xmlDeclaration0.attributes();
      attributes0.put("org.jsoup.nodes.XmlDeclaration", true);
      String string0 = xmlDeclaration0.toString();
      assertEquals("<!F org.jsoup.nodes.XmlDeclaration!>", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("ZM#v<=DdFqU-Kg", true);
      String string0 = xmlDeclaration0.getWholeDeclaration();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("A0+;T]/", "A0+;T]/", false);
      assertEquals(0, xmlDeclaration0.siblingIndex());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("", false);
      assertEquals("#declaration", xmlDeclaration0.nodeName());
      
      String string0 = xmlDeclaration0.toString();
      assertEquals("<??>", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("N>F", true);
      String string0 = xmlDeclaration0.name();
      assertEquals("N>F", string0);
      assertEquals("#declaration", xmlDeclaration0.nodeName());
  }
}
